### ISSUE TITLE
Facing issue while installing

### ISSUE THREAD

**Issue by ArulPushpam** [KayeeNL/sitecore-sif-autoinstall-publishingservice#2]
Hai @KayeeNL ,

I followed your way of installing the publishing service in my instance. But I am facing this error when I try to install
![image](https://user-images.githubusercontent.com/49192393/139116668-77181fde-f728-4e04-81ef-d2eab5674dc0.png)

**Comment by KayeeNL** [comment]
Never seen that unfortunately @ArulPushpam (and sorry for my late response ;-))

**Comment by KayeeNL** [comment]
Can't reproduce, sorry....
